require: rubocop-rspec

Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/FilePath:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5
